### ISSUE TITLE
rr algorithm

### ISSUE THREAD

**Issue by bakip** [facebookincubator/dhcplb#25]
If I use xid algorithm, I do not have any problem.

I0415 17:22:47.994353   17570 modulo.go:67] List of available stable servers:
I0415 17:22:47.994376   17570 modulo.go:69] Hostname: 10.8.2.100, IP: 10.8.2.100, Port: 67
I0415 17:22:47.994387   17570 modulo.go:69] Hostname: 10.8.2.101, IP: 10.8.2.101, Port: 67
I0415 17:23:01.064832   17570 glog_logger.go:104] client_mac: 00:50:56:aa:0a:79, dhcp_server: 10.8.2.100, giaddr: 10.0.1.252, latency_us: 144, server_is_rc: false, source_ip: 10.0.1.252, success: true, type: DISCOVER, version: 4, xid: 0x731a5494
I0415 17:23:01.069970   17570 glog_logger.go:104] client_mac: 00:50:56:aa:0a:79, dhcp_server: 10.8.2.100, giaddr: 10.0.1.252, latency_us: 47, server_is_rc: false, source_ip: 10.0.1.252, success: true, type: REQUEST, version: 4, xid: 0x731a5494
I0415 17:23:17.994353   17570 modulo.go:67] List of available stable servers:
I0415 17:23:17.994376   17570 modulo.go:69] Hostname: 10.8.2.100, IP: 10.8.2.100, Port: 67
I0415 17:23:17.994387   17570 modulo.go:69] Hostname: 10.8.2.101, IP: 10.8.2.101, Port: 67

But if I change rr algorithm, no packet is sent to dhcp servers also no periodic update available servers like stopped service.

I0415 17:51:28.471107   19507 main.go:78] Config changed
I0415 17:51:28.471110   19507 server.go:52] Updating server config
I0415 17:51:28.471113   19507 rr.go:82] List of available stable servers:
I0415 17:51:28.471117   19507 rr.go:84] Hostname: 10.8.2.100, IP: 10.8.2.100, Port: 67
I0415 17:51:28.471121   19507 rr.go:84] Hostname: 10.8.2.101, IP: 10.8.2.101, Port: 67
I0415 17:51:28.471125   19507 rr.go:82] List of available rc servers:
I0415 17:51:28.471129   19507 server.go:57] Updated server config

**Comment by pmazzini** [comment]
@bakip Thanks for reporting it. I'll take a look.

**Comment by pmazzini** [comment]
This should be fixed after 61000e8. Feel free to reopen if it is still an issue.
