### ISSUE TITLE
Value Change Problem

### ISSUE THREAD

**Issue by bakip** [facebookincubator/dhcplb#27]
When I change throttle values and port number, it does not change in run-time.

**Comment by pmazzini** [comment]
Hi @bakip, thanks for reporting it.

With regards to the throttle values I agree that we should be able to hot reload it. I will try to tackle it soon.

With regards to changing the port during run time, I don't know if that is a good idea. We currently bind to `listen_addr`:`port` just once when the server starts. The idea of hot reloading the config is to avoid missing traffic when changing the config, which could potentially happen if you are changing the port. Why not a restart in that case?

Is this a feature you are looking forward to have? What is your use case? The dhcp ports are  pretty standard ones.

**Comment by bakip** [comment]
I agree to your idea for port number, I just check configuration paramaters and I have no problem with the port number.

**Comment by pmazzini** [comment]
Great! I'll fix the hot reloading of throttle values then.

**Comment by pmazzini** [comment]
Sorry for the delay, I will get back to this soon.
