### ISSUE TITLE
"Chef Infra Client cannot execute without accepting the license" When trying to run "vagrant up"

### ISSUE THREAD

**Issue by eileenzliu** [facebookincubator/dhcplb#29]
When I tried to run "vagrant up", I got the following errors for all the VMs:
==> dhcpclient: Chef Infra Client cannot execute without accepting the license
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by pmazzini** [comment]
Ok, thanks for reporting, I'll take a look.

**Comment by eileenzliu** [comment]
> Ok, thanks for reporting, I'll take a look.

Thank you! If you need any more information, please let me know.

**Comment by pmazzini** [comment]
I checked the docs in https://docs.chef.io/chef_license_accept/#vagrant

Would you mind trying with the following line:

```
chef.arguments = "--chef-license accept"
```

In the vagrant file:

https://github.com/facebookincubator/dhcplb/blob/master/vagrant/Vagrantfile#L69

Thanks

**Comment by eileenzliu** [comment]
The license errors did go away after I made the changes in VagrantFile. Thank you!  

However, I am getting the following errors now when I tried to run “vagrant up”:

Do you know why?

Thanks,

-Eileen

==> dhcplb: * bash[Installing package github.com/facebookincubator/dhcplb] action run
==> dhcplb:
==> dhcplb:
==> dhcplb:
==> dhcplb: ================================================================================
==> dhcplb:
==> dhcplb: Error executing action `run` on resource 'bash[Installing package github.com/facebookincubator/dhcplb]'
==> dhcplb:       ================================================================================
==> dhcplb:
==> dhcplb:       Mixlib::ShellOut::ShellCommandFailed
==> dhcplb:       ------------------------------------
==> dhcplb:       Expected process to exit with [0], but received '1'
==> dhcplb:       ---- Begin output of "bash"  "/tmp/chef-script20200302-10179-et086o" ----
==> dhcplb:
==> dhcplb: STDOUT:
==> dhcplb:
==> dhcplb:
==> dhcplb: STDERR:
==> dhcplb:
==> dhcplb:
==> dhcplb: ---- End output of "bash"  "/tmp/chef-script20200302-10179-et086o" ----
==> dhcplb:
==> dhcplb:
==> dhcplb: Ran "bash"  "/tmp/chef-script20200302-10179-et086o" returned 1
==> dhcplb:
==> dhcplb:
==> dhcplb:
==> dhcplb:
==> dhcplb: Cookbook Trace:
==> dhcplb:       ---------------
==> dhcplb:       /var/chef/cache/cookbooks/golang/providers/package.rb:14:in `block in class_from_file'
==> dhcplb:
==> dhcplb:       Resource Declaration:
==> dhcplb:       ---------------------
==> dhcplb:       # In /var/chef/cache/cookbooks/golang/providers/package.rb
==> dhcplb:
==> dhcplb:         5:   bash "Installing package #{new_resource.name}" do
==> dhcplb:         6:     code "#{node['go']['install_dir']}/go/bin/go get -v #{new_resource.name} 2> >(grep -v '(download)$' > #{tmp_file_path})"
==> dhcplb:         7:     action :nothing
==> dhcplb:         8:     user node['go']['owner']
==> dhcplb:         9:     group node['go']['group']
==> dhcplb:        10:     environment({
==> dhcplb:        11:       'GOPATH' => node['go']['gopath'],
==> dhcplb:        12:       'GOBIN' => node['go']['gobin']
==> dhcplb:        13:     })
==> dhcplb:        14:   end.run_action(:run)
==> dhcplb:        15:
==> dhcplb:        16:   f = file tmp_file_path do
==> dhcplb:        17:     content ''
==> dhcplb:        18:   end
==> dhcplb:        19:   f.run_action(:create)
==> dhcplb:        20:
==> dhcplb:        21:   new_resource.updated_by_last_action(f.updated?)
==> dhcplb:        22: end
==> dhcplb:        23:
==> dhcplb:
==> dhcplb:       Compiled Resource:
==> dhcplb:       ------------------
==> dhcplb:       # Declared in /var/chef/cache/cookbooks/golang/providers/package.rb:5:in `block in class_from_file'
==> dhcplb:
==> dhcplb:       bash("Installing package github.com/facebookincubator/dhcplb") do
==> dhcplb:         action [:nothing]
==> dhcplb:         default_guard_interpreter :default
==> dhcplb:         command nil
==> dhcplb:         backup 5
==> dhcplb:         interpreter "bash"
==> dhcplb:         declared_type :bash
==> dhcplb:         cookbook_name "golang"
==> dhcplb:         code "/usr/local/go/bin/go get -v github.com/facebookincubator/dhcplb 2> >(grep -v '(download)$' > /var/chef/cache/github.com-facebookincubator-dhcplb)"
==> dhcplb:         domain nil
==> dhcplb:         user "root"
==> dhcplb:         environment {"GOPATH"=>"/opt/go", "GOBIN"=>"/opt/go/bin"}
==> dhcplb:         group "root"
==> dhcplb:       end
==> dhcplb:
==> dhcplb:
==> dhcplb:
==> dhcplb: System Info:
==> dhcplb:
==> dhcplb: ------------
==> dhcplb:
==> dhcplb: chef_version=15.1.36
==> dhcplb:
==> dhcplb:
==> dhcplb: platform=ubuntu
==> dhcplb:
==> dhcplb:
==> dhcplb: platform_version=14.04
==> dhcplb:
==> dhcplb:
==> dhcplb: ruby=ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
==> dhcplb:
==> dhcplb:
==> dhcplb: program_name=/usr/bin/chef-solo
==> dhcplb:
==> dhcplb:
==> dhcplb: executable=/opt/chef/bin/chef-solo
==> dhcplb:
==> dhcplb:
==> dhcplb:
==> dhcplb:
==> dhcplb:
==> dhcplb:
==> dhcplb: ================================================================================
==> dhcplb:
==> dhcplb: Error executing action `install` on resource 'golang_package[github.com/facebookincubator/dhcplb]'
==> dhcplb:
==> dhcplb: ================================================================================
==> dhcplb:
==> dhcplb:
==> dhcplb:     Mixlib::ShellOut::ShellCommandFailed
==> dhcplb:     ------------------------------------
==> dhcplb:     bash[Installing package github.com/facebookincubator/dhcplb] (/var/chef/cache/cookbooks/golang/providers/package.rb line 5) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> dhcplb:     ---- Begin output of "bash"  "/tmp/chef-script20200302-10179-et086o" ----
==> dhcplb:     STDOUT:
==> dhcplb:     STDERR:
==> dhcplb:     ---- End output of "bash"  "/tmp/chef-script20200302-10179-et086o" ----
==> dhcplb:     Ran "bash"  "/tmp/chef-script20200302-10179-et086o" returned 1
==> dhcplb:
==> dhcplb:     Cookbook Trace:
==> dhcplb:     ---------------
==> dhcplb:     /var/chef/cache/cookbooks/golang/providers/package.rb:14:in `block in class_from_file'
==> dhcplb:
==> dhcplb:     Resource Declaration:
==> dhcplb:     ---------------------
==> dhcplb:     # In /var/chef/cache/cookbooks/golang/recipes/packages.rb
==> dhcplb:
==> dhcplb:      23:   golang_package package
==> dhcplb:      24: end
==> dhcplb:
==> dhcplb:     Compiled Resource:
==> dhcplb:     ------------------
==> dhcplb:     # Declared in /var/chef/cache/cookbooks/golang/recipes/packages.rb:23:in `block in from_file'
==> dhcplb:
==> dhcplb:     golang_package("github.com/facebookincubator/dhcplb") do
==> dhcplb:       action [:install]
==> dhcplb:       default_guard_interpreter :default
==> dhcplb:       declared_type :golang_package
==> dhcplb:       cookbook_name "golang"
==> dhcplb:       recipe_name "packages"
==> dhcplb:     end
==> dhcplb:
==> dhcplb:     System Info:
==> dhcplb:     ------------
==> dhcplb:     chef_version=15.1.36
==> dhcplb:     platform=ubuntu
==> dhcplb:     platform_version=14.04
==> dhcplb:     ruby=ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
==> dhcplb:     program_name=/usr/bin/chef-solo
==> dhcplb:     executable=/opt/chef/bin/chef-solo
==> dhcplb:
==> dhcplb: [2020-03-02T00:20:42+00:00] INFO: Running queued delayed notifications before re-raising exception
==> dhcplb:
==> dhcplb: Running handlers:
==> dhcplb: [2020-03-02T00:20:42+00:00] ERROR: Running exception handlers
==> dhcplb: Running handlers complete
==> dhcplb: [2020-03-02T00:20:42+00:00] ERROR: Exception handlers complete
==> dhcplb: Chef Infra Client failed. 13 resources updated in 02 minutes 08 seconds
==> dhcplb: [2020-03-02T00:20:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> dhcplb: [2020-03-02T00:20:42+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> dhcplb: [2020-03-02T00:20:42+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: golang_package[github.com/facebookincubator/dhcplb] (golang::packages line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: bash[Installing package github.com/facebookincubator/dhcplb] (/var/chef/cache/cookbooks/golang/providers/package.rb line 5) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> dhcplb: ---- Begin output of "bash"  "/tmp/chef-script20200302-10179-et086o" ----
==> dhcplb: STDOUT:
==> dhcplb: STDERR:
==> dhcplb: ---- End output of "bash"  "/tmp/chef-script20200302-10179-et086o" ----
==> dhcplb: Ran "bash"  "/tmp/chef-script20200302-10179-et086o" returned 1
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by pmazzini** [comment]
Thanks for testing it.

Do things change if a more up to date version of Go is specified in:
https://github.com/facebookincubator/dhcplb/blob/master/vagrant/chef/cookbooks/dhcplb/recipes/default.rb#L6

For example 1.13.

**Comment by eileenzliu** [comment]
I changed it to 1.13. It works now. 

Thank you so much for the help!


-Eileen

**Comment by pmazzini** [comment]
Awesome. Thanks for testing it.

**Comment by eileenzliu** [comment]
Hi Pablo,

One thing I forgot the mentioned. The "brew cask install Caskroom/cask/chefdk” command didn’t work for me: https://github.com/facebookincubator/dhcplb/blob/master/vagrant/README.md <https://github.com/facebookincubator/dhcplb/blob/master/vagrant/README.md>. I have to manually install the chef-dk before everything starts working. 

Thank you for taking the time to fix the issues for me. 

-Eileen

**Comment by pmazzini** [comment]
Ok, thanks for the info. Did you get any error with that command? I don't own a Mac. Do you know if there is any command line that can be used instead to install it? Do you suggest anything to put in the README?

**Comment by eileenzliu** [comment]
I got the following errors:
$ brew cask install Caskroom/cask/chefdk
Error: Cask 'chefdk' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/chefdk.rb' does not exist.

I was able to install it using the following command:

$ brew cask install chef/chef/chefdk
==> Tapping chef/chef
Cloning into '/usr/local/Homebrew/Library/Taps/chef/homebrew-chef'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 749 (delta 17), reused 14 (delta 10), pack-reused 724
Receiving objects: 100% (749/749), 147.94 KiB | 1.17 MiB/s, done.
Resolving deltas: 100% (397/397), done.
Tapped 4 casks (42 files, 218.3KB).
==> Downloading https://packages.chef.io/files/stable/chefdk/4.7.73/mac_os_x/10.14/chefdk-4.7.73-1.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'chefdk'.
==> Installing Cask chefdk
==> Running installer for chefdk; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is ChefDK
installer: Upgrading at base path /
installer: The upgrade was successful.
🍺  chefdk was successfully installed!

Maybe you can just change the brew cask command in the README to use the new command?

Thanks,

-Eileen
