### ISSUE TITLE
Update the "Requirements" category section to latest way of installing libraries

### ISSUE THREAD

**Issue by aravindb26** [facebookincubator/dhcplb#37]
$ go get github.com/fsnotify/fsnotify
$ go get github.com/golang/glog
$ go get github.com/facebookgo/ensure
$ go get github.com/hashicorp/golang-lru
$ go get github.com/insomniacslk/dhcp/dhcpv4
$ go get github.com/insomniacslk/dhcp/dhcpv6
$ go get golang.org/x/time/rate

Update it to:
go install example.com/cmd@latest for an easy installation.

**Comment by pzmarzly** [comment]
Done, thanks!

**Comment by aravindb26** [comment]
Welcome ☺️

**Comment by aravindb26** [comment]
@pzmarzly Can we consider these as a bug?

**Comment by aravindb26** [comment]
@pzmarzly are you available? Can you consider it under bug?

**Comment by pzmarzly** [comment]
No. BTW back when the code was being written, `go install` didn't exist (it was introduced Go 1.16, so Feb 2021). Tech debt? Yeah, kinda, we could have revisited our projects after upgrading to Go 1.16.

**Comment by aravindb26** [comment]
@pzmarzly oh ok, It's fine

**Comment by aravindb26** [comment]
> 

But also I read in policy that causing difficulty in installation of the tool also considered as bug know? I mean insecure installation
<img width="413" alt="pr" src="https://user-images.githubusercontent.com/89305482/190898226-97aeb39f-ab2d-4622-8df9-954dd5ebd1d7.png">
