### ISSUE TITLE
Broken dependency with golang-lru

### ISSUE THREAD

**Issue by nelsonfbr** [facebookincubator/dhcplb#40]
Hello,

golang-lru has changed their main package:

"Please use `github.com/hashicorp/golang-lru/v2` for all new code as this
version supports generics and is faster; old code can specify a specific tag,
e.g.  `github.com/hashicorp/golang-lru/v0.6.0` for backwards compatibility. "

Can you fix the broken dependency with golang-lru?

Thanks.

**Comment by xaionaro** [comment]
O, now it uses generics? Nice :)

**Comment by pmazzini** [comment]
Closing after #41.
