### ISSUE TITLE
Vendor Dependencies

### ISSUE THREAD

**Issue by gsquire** [facebookincubator/dhcplb#7]
Considering modern go versions have vendor support, it would be easy to set this up instead of [listing them explicitly](https://github.com/facebookincubator/dhcplb#requirements).

It would add bloat to the codebase but it would make it easier to install for other users.

**Comment by pallotron** [comment]
The requirement chapter is redundant and you don't really need to run those `go get` commands. I put them just to clearly state what are the dependencies to build dhcplb. You really don't need vendor support to be honest.

`go get github.com/facebookincubator/dhcplb` will recurse thru dependencies, fetch & compile them, then put sources and binaries into your `$GOPATH/src` and `$GOPATH/bin` dirs.  As soon as you do that you will have `dhcplb` in your PATH (supposing your `$PATH` is properly set)

See:

```
$ echo $GOPATH
/Users/pallotron/go
$ rm -rf ~/go/src/*
$ rm -rf ~/go/bin/dhcplb
$ go get github.com/facebookincubator/dhcplb
$ which dhcplb
/Users/pallotron/go/bin/dhcplb
$ ls /Users/pallotron/go/src/github.com/
facebookincubator	fsnotify		golang			hashicorp		krolaw
$ ls /Users/pallotron/go/src/golang.org/x/
net	sys	time
```

If you want to develop it you will just need to fork this repo, then replace the `go get` with a `git clone`, then `go install` from the root dir of the project.
